service: my-used-cars-shop-app
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x


plugins:
  - serverless-finch


custom:
  client:
    bucketName: my-used-cars-shop-app
    distributionFolder: dist

functions:
  function1:
    handler: index.handler
